sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tomersf/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tomersf/docker-react npm run test